### PR TITLE
Signin highos

### PR DESCRIPTION
**Pull request by PatYo9**

### CODE REVIEW

**Comment by ldgmini** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">:memo: Please provide a summary in the Pull Request description</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">:memo: Please include a CHANGELOG entry. <br />
You can find it at <a href="https://github.com/mas-cli/mas/blob/master/CHANGELOG.md">CHANGELOG.md</a>.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">:dizzy_face: Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by phatblat** [comment]
@PatYo9 the `signin-highos` branch is not ready to be merged. The main issue I've been hoping to resolve is the signin functionality. The method `accountService.signIn(with: context)` worked in older versions of macOS, but was removed in High Sierra (10.13) and I have not been able to find an alternative.

Since this is part of a private framework, it is not supported by Apple, which limits our options.

**Comment by PatYo9** [comment]
Thanks👍👍 like to be informed.

Groeten,

Patrick

Verstuurd vanaf mijn iPhone

Op 1 jul. 2018 om 18:01 heeft Ben Chatelain <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@PatYo9<https://github.com/PatYo9> the signin-highos branch is not ready to be merged. The main issue I've been hoping to resolve is the signin functionality. The method accountService.signIn(with: context) worked in older versions of macOS, but was removed in High Sierra (10.13) and I have not been able to find an alternative.

Since this is part of a private framework, it is not supported by Apple, which limits our options.

**Comment by phatblat** [comment]
Superceded by 162

**Pull request closed without merging**
