### PR TITLE
🧹 Lint in GitHub Actions

### PR DESCRIPTION
**Pull request by chris-araman**
This no longer runs as part of the xcodebuild. If we wanted to, we could run it from swift build by creating a Process in Package.swift.

(Creating this PR again due to stalled check in the #375 due to the rename.)

### CODE REVIEW

**Comment by chris-araman** [comment]
🤔 Same stalled check here.

**Review by phatblat — APPROVED** [review]

**Comment by chris-araman** [comment]
@phatblat, this check stalled out. Are you able to merge around it?

**Comment by phatblat** [comment]
The addition of the build name changed the branch check. It was waiting for the old `build-test` job to complete. Branch config updated now.

**Comment by chris-araman** [comment]
Thanks!

**Comment by phatblat** [comment]
@chris-araman BTW, the "Admin" team I added you to isn't mapped to any repos 🤦🏻‍♂️, so I granted you the "Owner" role at the org level.

**Comment by chris-araman** [comment]
Cool, thanks!

**Pull request merged**
