### PR TITLE
👷🏻‍♂️ Add GitHub Actions Build & Test workflow

### PR DESCRIPTION
**Pull request by phatblat**
Due to the current issues with [Jenkins](https://jenkins.log-g.co/) this enables builds on GitHub Actions runners for our PR feedback.

Instead of #338

### CODE REVIEW

**Comment by phatblat** [comment]
It seems that SwiftLint 0.43.0 is already installed on the GitHub Actions `macOS-latest` nodes, so I removed it from the `Brewfile` for now.

```
==> Pouring swiftlint-0.43.0.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/swiftlint
Target /usr/local/bin/swiftlint
already exists. You may want to remove it:
  rm '/usr/local/bin/swiftlint'

To force the link and overwrite all conflicting files:
  brew link --overwrite swiftlint

To list all files that would be deleted:
  brew link --overwrite --dry-run swiftlint

Possible conflicting files are:
/usr/local/bin/swiftlint
==> Summary
🍺  /usr/local/Cellar/swiftlint/0.43.0: 6 files, 13.4MB
Installing swiftlint has failed!
```

**Comment by phatblat** [comment]
@chris-araman I got this working but had some issues with SwiftLint which you should review for #334

**Comment by chris-araman** [comment]
LGTM.

+1 for GitHub Actions. I've had good success with them. No support for M1 or macOS 11 yet, but they're working on it.

I think you can probably remove `Mintfile` here as well.

**Review by chris-araman — DISMISSED** [review]

**Review by chris-araman — APPROVED** [review]
:+1:

**Pull request merged**
