### PR TITLE
🔧 Check for mac updates only

### LINKED ISSUE #491: `outdated` lists latest iOS version instead of macOS version
## Your Environment

- `mas version`: 1.8.6
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 13.3.1 (22E261)

### mas Install Method

- [x] `brew install mas` (homebrew-core)
- [] [mas-cli/tap](https://github.com/mas-cli/homebrew-tap)
- [] `.pkg` installer from [releases](https://github.com/mas-cli/mas/releases)
- [] Built from source
  - Fork/branch: ? (e.g. mas-cli/main)
  - Xcode version: 10.?

## Describe the Bug

iOS app versions (mistakenly) being included (and compared) when checking outdated (Mac) apps

## To Reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Expected Behavior

`mas outdated` should not produce as output:

`967805235 Paste (3.1.9 -> 3.2)`

considering there exists no 3.2 version (yet) of the Paste app on the (Mac) App Store.

## Actual Behavior

At each invocation of

`mas upgrade`

Paste (version 3.1.9) will be (re)installed.
By checking with:

`mas outdated`

I get the following output (before, and as well after, invoking upgrade):

`967805235 Paste (3.1.9 -> 3.2)`

so I may guess this (unexpected) output to point right at the root cause.

In particular, there is no 3.2 release (yet), as I guess MAS is (mistakenly) checking the versions of the iOS flavour of the same App, as the iOS latest version of the app in the store indeed is at 3.2, and conflating/comparing the versions both from the Mac side and the iOS side. In this case, iOS version (3.2) would be the latest, compared to Mac version (3.1.9) and naturally take precedence, hence being listed among "outdated" apps.

## Screenshots, Terminal Output

> If applicable, add screenshots to help explain your problem.

```bash
$ mas command
...
```

## Additional Context

> Add any other context about the problem here.
> Did it work in a previous version?

### PR DESCRIPTION
**Pull request by WangEdward**
Attempt to fix #491, #336 (and some other dup issue)

This idea is from [https://github.com/mangerlahn/Latest](https://github.com/mangerlahn/Latest/blob/9e98e7317926597d98d323c43a562d6caeca21c7/Latest/Model/Update%20Checker%20Extensions/MacAppStoreCheckerOperation.swift#L114-L127)(Thanks!). They also added "macSoftware" param, which I believe is unnecessary for us as it is not possible to upgrade an iOS-only app from command-line. (Not 100% sure, if that causes problem, we can add the param in the future)

### CODE REVIEW

**Comment by antifuchs** [comment]
Just tested this manually, using `curl 'https://itunes.apple.com/lookup?id=1508732804&entity=desktopSoftware' | jq '.results[0].version'` (Soulver 3 is one of the apps that have a different version on the desktop and on iOS), and that returns the correct version number. I think this might finally solve the issue of phantom-outdated versions for real!

**Comment by rmehner** [comment]
Can confirm that this fixes things for me as well. Thank you @WangEdward!

**Comment by iamrecursion** [comment]
Glad to see a fix is in the works! I ran into this one recently.

**Comment by pawisoon** [comment]
Can we get this merged please? @phatblat

**Comment by nicerloop** [comment]
A custom formula for homebrew is available as nicerloop/nicerloop/mas in https://github.com/nicerloop/homebrew-nicerloop
Feel free to test.

**Comment by WafaAmr** [comment]
Can we get this merged please? @phatblat

**Review by rgoldberg — APPROVED** [review]
Looks good

**Comment by rgoldberg** [comment]
I haven't dealt with GitHub workflows before.

The workflow seems stuck at:

> Build, Test, and Lint Expected — Waiting for status to be reported

Must we "Bump actions/checkout from 3 to 4" via #500 to unstick the workflow?

I've seen suggestions to amend the PR's commit, but I'd prefer to avoid messing with the git commits if It can / must be fixed via the GibHub interface / configuration.

**Comment by rmehner** [comment]
Hi @rgoldberg,

thanks for having a look, I'm excited to see this finally going forward again :)

> Build, Test, and Lint Expected — Waiting for status to be reported
> Must we "Bump actions/checkout from 3 to 4" via https://github.com/mas-cli/mas/pull/500 to unstick the workflow?

This might solve the issue, if you rebase this branch then. If I'm not mistaken, it's merely an issue if retriggering the workflow that got stuck for whatever reason. The easiest way to do this is to add another commit to the PR / rebase the branch and then push again.

**Comment by WangEdward** [comment]
> The workflow seems stuck at:
> 
> > Build, Test, and Lint Expected — Waiting for status to be reported
> 
> Must we "Bump actions/checkout from 3 to 4" via #500 to unstick the workflow?

This is weird. There are [many pull requests open](https://github.com/mas-cli/mas/pulls), but non of them triggered the `Build, Test, and Lint` [workflow](https://github.com/mas-cli/mas/actions/workflows/build-test.yml) except #500. It seems to me that only pull requests from branch in the same repo can trigger the workflow. (Not sure about this, maybe there is something wrong related to [Branch protection rules](https://github.com/orgs/community/discussions/25720)?)

**Comment by GreyTeardrop** [comment]
According to GitHub docs, first-time contributors creating PRs from their pubic forks need maintainer approval before CI kicks in: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks.

**Comment by rgoldberg** [comment]
> According to GitHub docs, first-time contributors creating PRs from their pubic forks need maintainer approval before CI kicks in: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks.

@GreyTeardrop Thanks for the info. I don't see "Workflow(s) awaiting approval" anywhere, so I assume that I'm not authorized to approve workflows. I'm only a Member; the only Maintainer is @phatblat.

**Comment by rgoldberg** [comment]
@WangEdward @rmehner @GreyTeardrop

Thanks for the suggestions. I think that either @WangEdward should follow @rmehner's suggestion (potentially doing what's suggested at https://stackoverflow.com/a/58190576/2030088) or that I should try to make my own PR duplicating @WangEdward's one. I might have more success because I've already contributed & am a project Member, so I might be authorized to start workflows from my PRs, and because I'll use a branch other than `main`.

@WangEdward You choose what you want to do, as it's your PR. If I don't hear back from you in 48 hours or so, I'll just make my own PR, in which I'll credit you, just to keep everything moving.

Thanks for the fix.

**Comment by rgoldberg** [comment]
@MikeMcQuaid We're working on getting this merged & released. The regular maintainers are MIA, but I'm a project member (with no knowledge of the project's workflows, release procedures, etc.). I'll let you know when it's released so you'll be able to revert Homebrew/homebrew-bundle#1231.

**Comment by rgoldberg** [comment]
@WangEdward Do you mind if I make my own PR using a non-`main` branch to see if it works better for me?

**Comment by WangEdward** [comment]
> @WangEdward Do you mind if I make my own PR using a non-`main` branch to see if it works better for me?

Please feel free to do so. Maybe that will work. 😀

**Comment by MikeMcQuaid** [comment]
@rgoldberg thanks for the heads up. keep me posted!

**Comment by rgoldberg** [comment]
I don't see any runners listed on https://github.com/mas-cli/mas/actions/runners?tab=self-hosted.

I have no idea why `self-hosted` was specified without any currently extant runners. Maybe they previously existed but are now gone.

If anyone knows GitHub workflows, actions, etc. well, help will be appreciated.

@phatblat Any ideas? Is/was @ldgmini somehow related to the self-hosted runner? What does @masclibot do?

**Comment by antifuchs** [comment]
If this repo works like most repos on github, running the CI jobs will be blocked until a repository admin / owner approves running the workflow. That's independent of any base branch to the PR.

This behavior is supposed to prevent exfiltration of github actions secrets. But as we have all witnessed, it results in an unknown in-between state where nobody knows what's wrong if the repo owner isn't around to press the button.

**Comment by rgoldberg** [comment]
I saw an "Approve and Run" button for the 2 workflows; I clicked it. "Build, Test, and Lint / Build, Test, and Lint (pull_request)" might still fail for some reason, possibly because of a missing self-hosted runner. It looks like the runner might be supposed to pull the workflow from the queue rather than have the workflow pushed to it. If @phatblat had a runner that he manually ran (or that periodically looked for queued workflows but that no longer is running), then the workflow won't complete.

If it does fail again, if anyone knows about self-hosted runners, any help setting one up (or switching to a GitHub runner, etc.) would be appreciated.

**Comment by GreyTeardrop** [comment]
> I have no idea why `self-hosted` was specified without any currently extant runners. Maybe they previously existed but are now gone.

Looks like @phatblat switched from GitHub-hosted `macos-latest` runners to self-hosted in https://github.com/mas-cli/mas/pull/382.

**Comment by rgoldberg** [comment]
> Looks like @phatblat switched from GitHub-hosted `macos-latest` runners to self-hosted in https://github.com/mas-cli/mas/pull/382.

@GreyTeardrop Thanks for the research; it saved me looking through everything myself. I can try to look at reasons for the change later, and for fixes / workarounds, but I'll be busy for a little bit beforehand.

**Comment by GreyTeardrop** [comment]
@rgoldberg I was able to set up a self-hosted runner on my laptop with scripts from https://github.com/mas-cli/m1-github-actions-runner, attach it to my [fork](https://github.com/GreyTeardrop/mas), recreate this PR [in that fork](https://github.com/GreyTeardrop/mas/pull/1), and run [some CI for it](https://github.com/GreyTeardrop/mas/actions/runs/6790378582/job/18460481026). The CI run failed, probably because my laptop is on Sonoma and something has to be tweaked for it to properly build on Sonoma (oddly enough, the step that failed is "Lint", not "Build").

**Comment by rgoldberg** [comment]
@GreyTeardrop I was busy until now. Thanks again for your efforts.

I don't have an Apple Silicon Mac (I'm still running an Intel Mac), so I might not be able to setup a working runner.

Do you have any local logs for the CI run on your computer? Specifically for the Lint step?

It's possible that the problem is that `swiftlint` wasn't installed:

The [Brewfile](https://github.com/mas-cli/mas/blob/4c044d8b649989e924e11252b2e063a81c60d866/Brewfile) (which I assume is used by [script/bootstrap](https://github.com/mas-cli/mas/blob/4c044d8b649989e924e11252b2e063a81c60d866/script/bootstrap#L16)) doesn't install `swiftlint` (which is run in [script/lint](https://github.com/mas-cli/mas/blob/4c044d8b649989e924e11252b2e063a81c60d866/script/lint#L34C3-L34C12)), but it isn't included in macOS 12.7.1 (I don't know about macOS 13+). A comment mentions that it's "Already installed on GitHub Actions runner", but it's likely not already installed on your machine. If you uncomment [`brew "swiftlint"`](https://github.com/mas-cli/mas/blob/4c044d8b649989e924e11252b2e063a81c60d866/Brewfile#L7), maybe the Lint step will succeed.

The other linters used in [script/lint](https://github.com/mas-cli/mas/blob/4c044d8b649989e924e11252b2e063a81c60d866/script/lint) are listed in [Brewfile](https://github.com/mas-cli/mas/blob/4c044d8b649989e924e11252b2e063a81c60d866/Brewfile). `swift` & `shellcheck` are run, but are not listed in the [linter list](https://github.com/mas-cli/mas/blob/4c044d8b649989e924e11252b2e063a81c60d866/script/lint#L15); `swift` should be included with macOS at `/usr/bin/swift` (at least it is in macOS 12.7.1), but I don't think that `shellcheck` is included with macOS (it isn't in macOS 12.7.1).

The [Brewfile](https://github.com/mas-cli/mas/blob/4c044d8b649989e924e11252b2e063a81c60d866/Brewfile) doesn't install `swift` or `git`, but they should both be included in macOS in `/usr/bin/`.

Also note that [Makefile](https://github.com/mas-cli/mas/blob/4c044d8b649989e924e11252b2e063a81c60d866/Makefile) runs `swiftenv`, which must be installed from the `kylef/formulae` tap. I don't know why that would affect the Lint step, but not others, so I assume that's not the problem.

**Comment by rmehner** [comment]
@rgoldberg if you need a macos runner, you might be able to use the one https://tart.run provides. Example on how to do that is right on their landing page (the diff).

**Comment by rgoldberg** [comment]
> @rgoldberg if you need a macos runner, you might be able to use the one https://tart.run provides. Example on how to do that is right on their landing page (the diff).

@rmehner thanks for the info, but I don't have Apple Silicon; I'm still using Intel. It might useful for someone else who has Apple Silicon and who is willing to provide a runner.

**Comment by rmehner** [comment]
@rgoldberg tart provides the runner, so it doesn't run on your local machine.

**Comment by rgoldberg** [comment]
@rmehner It reads to me like Tart is virtualization software while Cirrus Runners is a service using Tart that provides GitHub Runners. While usage of Tart is free for fewer than 100 cores, Cirrus Runners cost $150 / month each. Maybe I'm mistaken, but that's what it reads like to me. Do you have any link to any information that shows otherwise?

**Comment by GreyTeardrop** [comment]
> Do you have any local logs for the CI run on your computer? Specifically for the Lint step?

It doesn't seem to write any logs locally, apparently everything meaningful is streamed to the Actions console:
```
> ./start.sh

√ Connected to GitHub

Current runner version: '2.311.0'
2023-11-07 21:41:17Z: Listening for Jobs
2023-11-07 21:41:40Z: Running job: Build, Test, and Lint
2023-11-07 21:47:07Z: Job Build, Test, and Lint completed with result: Failed
^CExiting...
Runner listener exit with 0 return code, stop the service, no retry needed.
Exiting runner...
```

> It's possible that the problem is that swiftlint wasn't installed:

Based on what I see in the script, it should [install `swiftlint` automatically](https://github.com/mas-cli/mas/blob/4c044d8b649989e924e11252b2e063a81c60d866/script/bootstrap#L19-L21) if one isn't present.

I'll see what else can be done a bit later.

**Comment by rgoldberg** [comment]
Probably simplest to just delete everything from `script/lint` to make it a no-op.

> Based on what I see in the script, it should [install `swiftlint` automatically](https://github.com/mas-cli/mas/blob/4c044d8b649989e924e11252b2e063a81c60d866/script/bootstrap#L19-L21) if one isn't present.

Thanks. I didn't continue reading `script/bootstrap` after the call to `brew bundle …` or search for `swiftlint` after seeing the commented line in `Brewfile`. It's odd that they handle `swiftlint` differently instead of through `Brewfile`. You would think that `Brewfile` could handle a formula that is already installed…

**Comment by phatblat** [comment]
Sorry for the delay everyone. I've been swamped with work lately and haven't had time for open source contributions. I'm working on testing this now.

**Comment by GreyTeardrop** [comment]
GitHub made M1 runners available for free for open-source projects: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/ 🎉

**Comment by rgoldberg** [comment]
@GreyTeardrop See #508

**Comment by phatblat** [comment]
> @rgoldberg if you need a macos runner, you might be able to use the one https://tart.run provides. Example on how to do that is right on their landing page (the diff).

@rmehner I love [tart](https://tart.run)! [Cirrus' tart runners](https://tart.run/integrations/github-actions/#pricing) cost $150 per month. #509 switched back to GitHub-hosted runners, free for open source projects like this one.

**Comment by astrostl** [comment]
Is this coming soon? I love using `mas` via `brew bundle` but I'm about to give up on it over constant fake upgrades. Thanks!

**Comment by astrostl** [comment]
If I understand correctly, a fix for the long-standing fake upgrade problem already exists and is merged, but not released. What is standing in the way of that? Thanks!

**Comment by tonyarnold** [comment]
@phatblat can I help out with administrative load here? I'm happy to do PR review, releases, whatever helps to keep things moving while you're busy.

**Comment by phatblat** [comment]
@tonyarnold That would help immensely. I'm traveling in Japan for another couple weeks.

I worked up a release action in #510 but had trouble testing it with a pre release. #506 is the next action item but that was hard to delegate to someone without homebrew experience.

**Comment by tonyarnold** [comment]
No problems, I'll get a brew allowlist into place in the local tap, which should help with the workflow.

**Pull request merged**
