### PR TITLE
Only check for macOS updates, ignoring other platforms like iOS, iPadOS, etc.

### LINKED ISSUE #336: Confuses macOS and iOS/iPadOS apps
## Your Environment

- `mas version`: 1.8.1
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 11.2.3 (20D91)

### mas Install Method

`brew install mas` (homebrew-core)

## Describe the Bug

This is probably a problem with Apple's store APIs, not with mas.

Apple released Pages, Numbers & Keynote 11.0 on 2021-03-22.

mas commands list the current store version of each of them as 10.3.9, which is the version that is installed on my machine.

The App Store GUI doesn't show these as updates in the "Updates" tab, and the apps have Open buttons (instead of Update buttons) in my Account tab Purchased section.

If I look at the pages for these 3 apps in the App Store GUI, or see them in search results, then they have Update buttons (instead of Open buttons).  After seeing an Update button for one of these apps, the Open button in the Purchased section of the Account tab becomes am Update button until I close & reopen the App Store GUI.

## To Reproduce

1. See description above

## Expected Behavior

mas indicates that the store versions of Pages, Numbers & Keynote are now 11.0

Even though the App Store GUI is inconsistent, it would be nice if mas could be better than the GUI.

## Actual Behavior

mas indicates that the store versions of Pages, Numbers & Keynote are still 10.3.9

### PR DESCRIPTION
**Pull request by rgoldberg**
Only check for macOS updates, ignoring other platforms like iOS, iPadOS, etc.

Copied from PR #496 by @WangEdward

Resolves #336 & #491

### CODE REVIEW

**Comment by phatblat** [comment]
@rgoldberg I'm in Scotland this week but will review then when I'm back in Denver next week. Sorry, the macOS actions runner is offline

**Comment by rgoldberg** [comment]
@phatblat Thanks for the heads up.

This was just a copy of #496 but committed by me since we initially weren't sure why the test was failing. We figured out that the test machine was offline, so someone else with an Apple Silicon Mac (I still use an Intel) is trying to set one up, but the Lint step is failing. They're working on it from their end.

Enjoy Scotland!

**Comment by rgoldberg** [comment]
@phatblat Hope Scotland was fun.

Anything I can do to help get this (or #496) merged?

Thanks for any assistance.

**Comment by phatblat** [comment]
@rgoldberg I'm working on this today. Not sure if I'll be able to get my actions runner back online - the Mac mini needs some maintenance. Regardless, I can test this locally and work on getting a release out.

**Comment by rgoldberg** [comment]
@phatblat Thanks! Hope you had a happy Thanksgiving.

**Comment by rgoldberg** [comment]
@phatblat Not sure if you saw my comment on your PR:

https://github.com/mas-cli/mas/pull/

**Pull request closed without merging**
