### PR TITLE
Lucky command

### PR DESCRIPTION
**Pull request by pablopunk**
So, when I install apps, like 90% of the times I know I'm gonna install the one that appears in the first result of `mas search`. That's why I always wanted a _I'm feeling lucky_ feature.

Basically, it's a new command that searches an app name and installs the first result.

```bash
$ mas lucky twitter
==> Downloading Twitter
==> Installed Twitter
```
  
> EDIT
> As a workaround, you can use [this](https://github.com/mas-cli/mas/pull/88#issuecomment-356345009)

### CODE REVIEW

**Comment by pablopunk** [comment]
The tests are failing because the build process doesn't find `xcpretty`. Travis is not configured to have this so I guess I shouldn't commit here the fix for this.

**Comment by phatblat** [comment]
Build is fixed in #91

**Comment by pablopunk** [comment]
This repo isn't maintained very often is it?

**Comment by phatblat** [comment]
Nope. I reached out to @rodionovd a few weeks ago via email and offered help, but I haven't received a response.

**Comment by pablopunk** [comment]
Oh, I was thinking about doing that... I think there would be a lot of people interested in collaborate on this

**Comment by phatblat** [comment]
I'm tempted to try to release from a fork but I don't know what the process is for changing ownership of a brew formula

**Comment by rodionovd** [comment]
@pablopunk @phatblat 

I'm sooo sorry that I haven't reached back to you folks  — it's been a crazy few month for me but I'm back now and will go through all of the issues/PRs within next few days.

I really appreciate your patience and your hard work on PRs ❤️  You're awesome!

**Comment by pablopunk** [comment]
This doesn't seem to be maintained anymore. If anyone is interested on this feature, what I do is having this function on my `~/.bash_profile`:

```bash
function masl {
  mas search $1 | head -n1 | awk '{print $1;}' | xargs mas install
}
```

And then use it like:

```bash
$ masl Twitter
```

**Comment by phatblat** [comment]
@pablopunk the `master` branch has been updated to Swift 4 and after merging into your branch there are a couple of [syntax errors](https://travis-ci.org/mas-cli/mas/builds/334177305#L943). Could you fix those up so that I can merge this PR? Thanks!

**Comment by pablopunk** [comment]
@phatblat nice! I will do it

**Comment by phatblat** [comment]
Thanks, @pablopunk! This new command will go out in 1.4

**Comment by pablopunk** [comment]
@phatblat Awesome! Almost a year later 😄. I see took this repo, nice.

BTW I have no idea about Swift, I coded this basically copying `Install` and `Search` commands, so now it's only duplicated code. It works but it should be refactored to prevent code duplication.

**Comment by phatblat** [comment]
Could have fooled me! No worries about the duplicated code. I'll be doing some refactoring soon, but wanted to get the great features that have been waiting a long time into this great project.

**Pull request merged**
