### PR TITLE
Apple silicon GitHub hosted runner

### PR DESCRIPTION
**Pull request by GreyTeardrop**
Pulling @rgoldberg changes from https://github.com/mas-cli/mas/pull/508.

### CODE REVIEW

**Comment by GreyTeardrop** [comment]
@rgoldberg the workflow is paused and needs an approval.

**Comment by rgoldberg** [comment]
@GreyTeardrop Can you request that I review this PR?

I already approved, but that only ran the checks. Either `mas-cli/admins` must approve to merge, or you need to request me to review it, then I need to approve it. I assume the former is the case, but won't hurt to try as review request from you to me.

**Comment by GreyTeardrop** [comment]
Nope, I don't have an option to request any review :-(

**Comment by rgoldberg** [comment]
@GreyTeardrop Sorry, didn't know you wouldn't be able to request a review. I self-requested, but didn't see an option to approve the self-request. I'll try to get more permissions…

**Review by phatblat — COMMENTED** [review]
Great work. Thanks, @GreyTeardrop

**Review by phatblat — APPROVED** [review]

**Pull request merged**
