### PR TITLE
🚧 macOS Installers

### LINKED ISSUE #139: What's the difference between "id: Install" and "id: 0"?
I noticed a change in my Brewfile:

``` diff
-mas "macOS High Sierra", id: Install
+mas "Install macOS High Sierra", id: 0
```

Does it mean the update has been downloaded / installed?

### PR DESCRIPTION
**Pull request by phatblat**
Special handling for macOS installers.

```
$ mas os
==> Available macOS Installers:
  - Mojave 10.14 (1398502828) https://itunes.apple.com/us/app/macos-mojave/id1398502828?mt=12
  - High Sierra 10.13 (1246284741) https://itunes.apple.com/us/app/macos-high-sierra/id1246284741?mt=12
  - Sierra 10.12 (1127487414) https://itunes.apple.com/us/app/macos-sierra/id1127487414?mt=12
  - El Capitan 10.11 (1147835434) https://itunes.apple.com/us/app/os-x-el-capitan/id1147835434?mt=12
  - Yosemite 10.10 (915041082)
  - Mavericks 10.9 (675248567)
```

## 🚧  WIP

- [x] Installer data
- [x] String tokens for each macOS version (precursor to #109)
- [x] `install` command support
   -  Screen Shot 2019-03-30 at 4 35 15 PM
- [x] `list` command support (fixes #139)
- [ ] `home` command support 
- [ ] `open` command support 
- [ ] `vendor` command support 
- [ ] `uninstall` command support 
- [ ] `search` command support

### Mojave 10.14.4

Something changed in the latest Mojave update and a few of the 6 supported versions of macOS installers stopped working and instead give the following error:

Screen Shot 2019-03-30 at 4 27 03 PM

Most notably, this is affecting Mojave 😫

The behavior of downloading these installers also changed. I can still `mas open 1398502828` to open the Mojave page in the Mac App Store. Clicking the "GET" button opens the Software Update pane of System Preferences. So, looks like this functionality is moving out of the app store, just as I'm trying to add it to `mas`.

### CODE REVIEW

**Comment by Rohan200220** [comment]
Is it possible to install the installers that have not been purchased or linked to the Apple ID?

**Comment by phatblat** [comment]
@Rohan200220 perhaps. This PR is mainly to make the process of finding and installing the macOS installer apps easier. I would love to see if I can get it to work without being logged in but haven't figure out whether that is possible yet. #144

**Comment by koliberek0302** [comment]
`
- #```
```
```
```










```
```
```
````

**Comment by phatblat** [comment]
Closing this as it is quite stale now and interest has waned.

**Comment by startergo** [comment]
So is there a way to test it on earlier Mojave or the latest HS version. There is only one macOS which could not be downloaded from Apple servers without previous download newer than Lion, which is Mavericks. Mavericks was the first free macOS installer [Mavericks](https://www.apple.com/newsroom/2013/10/23OS-X-Mavericks-Available-Today-Free-from-the-Mac-App-Store/) yet it is not available for download.

**Pull request closed without merging**
